IF NOT EXISTS (
    SELECT * 
    FROM sys.columns 
    WHERE Name = N'RETRY_COUNT' AND Object_ID = Object_ID(N'ECRITURE_LOT')
)
BEGIN
    ALTER TABLE ECRITURE_LOT ADD RETRY_COUNT INT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (
    SELECT * 
    FROM sys.columns 
    WHERE Name = N'PENNYLANE_STATUS' AND Object_ID = Object_ID(N'ECRITURE_LOT')
)
BEGIN
    ALTER TABLE ECRITURE_LOT ADD PENNYLANE_STATUS VARCHAR(50) NULL;
END
