-- Vérifier si les colonnes existent déjà pour éviter les erreurs
IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'REGLEMENT' AND COLUMN_NAME = 'ID_TRANSACTION_PENNYLANE'
)
BEGIN
    -- Ajouter la colonne 'PENNYLANE_ID' de type VARCHAR(255)
    ALTER TABLE REGLEMENT ADD ID_TRANSACTION_PENNYLANE VARCHAR(255);
END;