-- Vérifier si les colonnes existent déjà pour éviter les erreurs
IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'SOCIETE_EXPORT' AND COLUMN_NAME = 'PENNYLANE_ID'
)
BEGIN
    -- Ajouter la colonne 'PENNYLANE_ID' de type VARCHAR(255)
    ALTER TABLE SOCIETE_EXPORT ADD PENNYLANE_ID VARCHAR(255);
END;
