-- Vérifie si MAX_RETRY existe déjà avant d'insérer
IF NOT EXISTS (SELECT 1 
               FROM T_PARAMETRE 
               WHERE VARIABLE = 'MAX_RETRY' 
                 AND PARAGRAPHE = 'PROCESS_RETRY')
BEGIN
    INSERT INTO T_PARAMETRE (VARIABLE, VALEUR, PARAGRAPHE)
    VALUES ('MAX_RETRY', '5', 'PROCESS_RETRY');
END

-- Vérifie si RETRY_DELAY existe déjà avant d'insérer
IF NOT EXISTS (SELECT 1 
               FROM T_PARAMETRE 
               WHERE VARIABLE = 'RETRY_DELAY' 
                 AND PARAGRAPHE = 'PROCESS_RETRY')
BEGIN
    INSERT INTO T_PARAMETRE (VARIABLE, VALEUR, PARAGRAPHE)
    VALUES ('RETRY_DELAY', '60', 'PROCESS_RETRY');
END
