INSERT INTO T_PARAMETRE (VARIABLE, VALEUR, PARAGRAPHE) VALUES ('MAX_RETRY', '5', 'PROCESS_RETRY');
INSERT INTO T_PARAMETRE (VARIABLE, VALEUR, PARAGRAPHE) VALUES ('RETRY_DELAY', '60', 'PROCESS_RETRY'); -- 60 minutes
