-- Vérifier si les colonnes existent déjà pour éviter les erreurs
IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'T_SITE' AND COLUMN_NAME = 'PENNYLANE_TOKEN'
)
BEGIN
    -- Ajouter la colonne 'PENNYLANE_TOKEN' de type VARCHAR(255)
    ALTER TABLE T_SITE ADD PENNYLANE_TOKEN VARCHAR(255);
END;

IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'T_SITE' AND COLUMN_NAME = 'PENNYLANE_ACTIF'
)
BEGIN
    -- Ajouter la colonne 'PENNYLANE_ACTIF' de type BIT
    ALTER TABLE T_SITE ADD PENNYLANE_ACTIF BIT DEFAULT 0;
END;

IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'T_SITE' AND COLUMN_NAME = 'PENNYLANE_ACHAT'
)
BEGIN
    -- Ajouter la colonne 'PENNYLANE_ACHAT' de type BIT
    ALTER TABLE T_SITE ADD PENNYLANE_ACHAT BIT DEFAULT 0;
END;