-- Vérifier si les colonnes existent déjà pour éviter les erreurs
IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'T_TAXES' AND COLUMN_NAME = 'CODE_CPTE_TAXE_PENNYLANE'
)
BEGIN
    -- Ajouter la colonne 'CODE_CPTE_TAXE_PENNYLANE' de type VARCHAR(50)
    ALTER TABLE T_TAXES ADD CODE_CPTE_TAXE_PENNYLANE VARCHAR(50);
END;