-- Vérifier si les colonnes existent déjà pour éviter les erreurs
IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'V_FACTURE' AND COLUMN_NAME = 'PENNYLANE_ID'
)
BEGIN
    -- Ajouter la colonne 'PENNYLANE_ID' de type VARCHAR(255)
    ALTER TABLE V_FACTURE ADD PENNYLANE_ID VARCHAR(255);
END;

-- Vérifier si les colonnes existent déjà pour éviter les erreurs
IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'V_FACTURE' AND COLUMN_NAME = 'PENNYLANE_ID_V2'
)
BEGIN
    -- Ajouter la colonne 'PENNYLANE_ID' de type VARCHAR(255)
    ALTER TABLE V_FACTURE ADD PENNYLANE_ID_V2 VARCHAR(255);
END;